name: aitorch
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - contourpy=1.3.0=py39h74842e3_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cython=3.0.12=py39hbce0bbb_0
  - fonttools=4.56.0=py39h9399b63_0
  - freetype=2.12.1=h4a9f257_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h0b41bf4_3
  - kiwisolver=1.4.7=py39h74842e3_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libdeflate=1.7=h7f98852_5
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libwebp-base=1.5.0=h851e524_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.9.4=py39h16632d1_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - numpy=2.0.2=py39h9cb892a_1
  - olefile=0.47=pyhd8ed1ab_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=3.4.1=h7b32b05_0
  - packaging=24.2=pyhd8ed1ab_2
  - pip=25.0=py39h06a4308_0
  - pycocotools=2.0.8=py39hf3d9206_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - qhull=2020.2=h4bd325d_2
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025a=h04d1e81_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - albucore==0.0.23
      - albumentations==2.0.5
      - annotated-types==0.7.0
      - eval-type-backport==0.2.2
      - filelock==3.17.0
      - fsspec==2025.3.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pillow==11.1.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyyaml==6.0.2
      - scipy==1.13.1
      - simsimd==6.2.1
      - stringzilla==3.12.2
      - sympy==1.13.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
prefix: /home/dmitry/anaconda3/envs/aitorch
